// // Mocks generated by Mockito 5.4.6 from annotations
// // in balance_sheet/test/security_trash_test.dart.
// // Do not manually edit this file.

// // ignore_for_file: no_leading_underscores_for_library_prefixes
// import 'dart:async' as _i3;
// import 'dart:ui' as _i7;

// import 'package:balance_sheet/controllers/security_controller.dart' as _i4;
// import 'package:get/get.dart' as _i2;
// import 'package:get/get_state_manager/src/simple/list_notifier.dart' as _i6;
// import 'package:mockito/mockito.dart' as _i1;
// import 'package:mockito/src/dummies.dart' as _i5;

// // ignore_for_file: type=lint
// // ignore_for_file: avoid_redundant_argument_values
// // ignore_for_file: avoid_setters_without_getters
// // ignore_for_file: comment_references
// // ignore_for_file: deprecated_member_use
// // ignore_for_file: deprecated_member_use_from_same_package
// // ignore_for_file: implementation_imports
// // ignore_for_file: invalid_use_of_visible_for_testing_member
// // ignore_for_file: must_be_immutable
// // ignore_for_file: prefer_const_constructors
// // ignore_for_file: unnecessary_parenthesis
// // ignore_for_file: camel_case_types
// // ignore_for_file: subtype_of_sealed_class
// // ignore_for_file: invalid_use_of_internal_member

// class _FakeRxBool_0 extends _i1.SmartFake implements _i2.RxBool {
//   _FakeRxBool_0(
//     Object parent,
//     Invocation parentInvocation,
//   ) : super(
//           parent,
//           parentInvocation,
//         );
// }

// class _FakeRxString_1 extends _i1.SmartFake implements _i2.RxString {
//   _FakeRxString_1(
//     Object parent,
//     Invocation parentInvocation,
//   ) : super(
//           parent,
//           parentInvocation,
//         );
// }

// class _FakeInternalFinalCallback_2<T> extends _i1.SmartFake
//     implements _i2.InternalFinalCallback<T> {
//   _FakeInternalFinalCallback_2(
//     Object parent,
//     Invocation parentInvocation,
//   ) : super(
//           parent,
//           parentInvocation,
//         );
// }

// class _FakeFuture_3<T1> extends _i1.SmartFake implements _i3.Future<T1> {
//   _FakeFuture_3(
//     Object parent,
//     Invocation parentInvocation,
//   ) : super(
//           parent,
//           parentInvocation,
//         );
// }

// /// A class which mocks [SecurityController].
// ///
// /// See the documentation for Mockito's code generation for more information.
// class MockSecurityController extends _i1.Mock
//     implements _i4.SecurityController {
//   @override
//   _i2.RxBool get pinIsSet => (super.noSuchMethod(
//         Invocation.getter(#pinIsSet),
//         returnValue: _FakeRxBool_0(
//           this,
//           Invocation.getter(#pinIsSet),
//         ),
//         returnValueForMissingStub: _FakeRxBool_0(
//           this,
//           Invocation.getter(#pinIsSet),
//         ),
//       ) as _i2.RxBool);

//   @override
//   _i2.RxString get currentPinEnteredByUser => (super.noSuchMethod(
//         Invocation.getter(#currentPinEnteredByUser),
//         returnValue: _FakeRxString_1(
//           this,
//           Invocation.getter(#currentPinEnteredByUser),
//         ),
//         returnValueForMissingStub: _FakeRxString_1(
//           this,
//           Invocation.getter(#currentPinEnteredByUser),
//         ),
//       ) as _i2.RxString);

//   @override
//   _i2.RxString get newPin => (super.noSuchMethod(
//         Invocation.getter(#newPin),
//         returnValue: _FakeRxString_1(
//           this,
//           Invocation.getter(#newPin),
//         ),
//         returnValueForMissingStub: _FakeRxString_1(
//           this,
//           Invocation.getter(#newPin),
//         ),
//       ) as _i2.RxString);

//   @override
//   _i2.RxString get verifyPin => (super.noSuchMethod(
//         Invocation.getter(#verifyPin),
//         returnValue: _FakeRxString_1(
//           this,
//           Invocation.getter(#verifyPin),
//         ),
//         returnValueForMissingStub: _FakeRxString_1(
//           this,
//           Invocation.getter(#verifyPin),
//         ),
//       ) as _i2.RxString);

//   @override
//   _i2.RxBool get showNewPin => (super.noSuchMethod(
//         Invocation.getter(#showNewPin),
//         returnValue: _FakeRxBool_0(
//           this,
//           Invocation.getter(#showNewPin),
//         ),
//         returnValueForMissingStub: _FakeRxBool_0(
//           this,
//           Invocation.getter(#showNewPin),
//         ),
//       ) as _i2.RxBool);

//   @override
//   _i2.RxBool get showVerifyInput => (super.noSuchMethod(
//         Invocation.getter(#showVerifyInput),
//         returnValue: _FakeRxBool_0(
//           this,
//           Invocation.getter(#showVerifyInput),
//         ),
//         returnValueForMissingStub: _FakeRxBool_0(
//           this,
//           Invocation.getter(#showVerifyInput),
//         ),
//       ) as _i2.RxBool);

//   @override
//   _i2.RxBool get fromSettings => (super.noSuchMethod(
//         Invocation.getter(#fromSettings),
//         returnValue: _FakeRxBool_0(
//           this,
//           Invocation.getter(#fromSettings),
//         ),
//         returnValueForMissingStub: _FakeRxBool_0(
//           this,
//           Invocation.getter(#fromSettings),
//         ),
//       ) as _i2.RxBool);

//   @override
//   _i2.RxBool get fingerprintInUse => (super.noSuchMethod(
//         Invocation.getter(#fingerprintInUse),
//         returnValue: _FakeRxBool_0(
//           this,
//           Invocation.getter(#fingerprintInUse),
//         ),
//         returnValueForMissingStub: _FakeRxBool_0(
//           this,
//           Invocation.getter(#fingerprintInUse),
//         ),
//       ) as _i2.RxBool);

//   @override
//   _i2.RxBool get sessionUnlocked => (super.noSuchMethod(
//         Invocation.getter(#sessionUnlocked),
//         returnValue: _FakeRxBool_0(
//           this,
//           Invocation.getter(#sessionUnlocked),
//         ),
//         returnValueForMissingStub: _FakeRxBool_0(
//           this,
//           Invocation.getter(#sessionUnlocked),
//         ),
//       ) as _i2.RxBool);

//   @override
//   bool get isSubFlowActive => (super.noSuchMethod(
//         Invocation.getter(#isSubFlowActive),
//         returnValue: false,
//         returnValueForMissingStub: false,
//       ) as bool);

//   @override
//   set currentPinEnteredByUser(_i2.RxString? value) => super.noSuchMethod(
//         Invocation.setter(
//           #currentPinEnteredByUser,
//           value,
//         ),
//         returnValueForMissingStub: null,
//       );

//   @override
//   set newPin(_i2.RxString? value) => super.noSuchMethod(
//         Invocation.setter(
//           #newPin,
//           value,
//         ),
//         returnValueForMissingStub: null,
//       );

//   @override
//   set verifyPin(_i2.RxString? value) => super.noSuchMethod(
//         Invocation.setter(
//           #verifyPin,
//           value,
//         ),
//         returnValueForMissingStub: null,
//       );

//   @override
//   set showNewPin(_i2.RxBool? value) => super.noSuchMethod(
//         Invocation.setter(
//           #showNewPin,
//           value,
//         ),
//         returnValueForMissingStub: null,
//       );

//   @override
//   set showVerifyInput(_i2.RxBool? value) => super.noSuchMethod(
//         Invocation.setter(
//           #showVerifyInput,
//           value,
//         ),
//         returnValueForMissingStub: null,
//       );

//   @override
//   set fromSettings(_i2.RxBool? value) => super.noSuchMethod(
//         Invocation.setter(
//           #fromSettings,
//           value,
//         ),
//         returnValueForMissingStub: null,
//       );

//   @override
//   set fingerprintInUse(_i2.RxBool? value) => super.noSuchMethod(
//         Invocation.setter(
//           #fingerprintInUse,
//           value,
//         ),
//         returnValueForMissingStub: null,
//       );

//   @override
//   _i2.InternalFinalCallback<void> get onStart => (super.noSuchMethod(
//         Invocation.getter(#onStart),
//         returnValue: _FakeInternalFinalCallback_2<void>(
//           this,
//           Invocation.getter(#onStart),
//         ),
//         returnValueForMissingStub: _FakeInternalFinalCallback_2<void>(
//           this,
//           Invocation.getter(#onStart),
//         ),
//       ) as _i2.InternalFinalCallback<void>);

//   @override
//   _i2.InternalFinalCallback<void> get onDelete => (super.noSuchMethod(
//         Invocation.getter(#onDelete),
//         returnValue: _FakeInternalFinalCallback_2<void>(
//           this,
//           Invocation.getter(#onDelete),
//         ),
//         returnValueForMissingStub: _FakeInternalFinalCallback_2<void>(
//           this,
//           Invocation.getter(#onDelete),
//         ),
//       ) as _i2.InternalFinalCallback<void>);

//   @override
//   bool get initialized => (super.noSuchMethod(
//         Invocation.getter(#initialized),
//         returnValue: false,
//         returnValueForMissingStub: false,
//       ) as bool);

//   @override
//   bool get isClosed => (super.noSuchMethod(
//         Invocation.getter(#isClosed),
//         returnValue: false,
//         returnValueForMissingStub: false,
//       ) as bool);

//   @override
//   bool get hasListeners => (super.noSuchMethod(
//         Invocation.getter(#hasListeners),
//         returnValue: false,
//         returnValueForMissingStub: false,
//       ) as bool);

//   @override
//   int get listeners => (super.noSuchMethod(
//         Invocation.getter(#listeners),
//         returnValue: 0,
//         returnValueForMissingStub: 0,
//       ) as int);

//   @override
//   _i3.Future<T> runWithSubFlow<T>(_i3.Future<T> Function()? body) =>
//       (super.noSuchMethod(
//         Invocation.method(
//           #runWithSubFlow,
//           [body],
//         ),
//         returnValue: _i5.ifNotNull(
//               _i5.dummyValueOrNull<T>(
//                 this,
//                 Invocation.method(
//                   #runWithSubFlow,
//                   [body],
//                 ),
//               ),
//               (T v) => _i3.Future<T>.value(v),
//             ) ??
//             _FakeFuture_3<T>(
//               this,
//               Invocation.method(
//                 #runWithSubFlow,
//                 [body],
//               ),
//             ),
//         returnValueForMissingStub: _i5.ifNotNull(
//               _i5.dummyValueOrNull<T>(
//                 this,
//                 Invocation.method(
//                   #runWithSubFlow,
//                   [body],
//                 ),
//               ),
//               (T v) => _i3.Future<T>.value(v),
//             ) ??
//             _FakeFuture_3<T>(
//               this,
//               Invocation.method(
//                 #runWithSubFlow,
//                 [body],
//               ),
//             ),
//       ) as _i3.Future<T>);

//   @override
//   void onReady() => super.noSuchMethod(
//         Invocation.method(
//           #onReady,
//           [],
//         ),
//         returnValueForMissingStub: null,
//       );

//   @override
//   void reloadFromStorage() => super.noSuchMethod(
//         Invocation.method(
//           #reloadFromStorage,
//           [],
//         ),
//         returnValueForMissingStub: null,
//       );

//   @override
//   void onRequireScreenLock() => super.noSuchMethod(
//         Invocation.method(
//           #onRequireScreenLock,
//           [],
//         ),
//         returnValueForMissingStub: null,
//       );

//   @override
//   void markSessionUnlocked() => super.noSuchMethod(
//         Invocation.method(
//           #markSessionUnlocked,
//           [],
//         ),
//         returnValueForMissingStub: null,
//       );

//   @override
//   dynamic setValueInStorage(
//     String? key,
//     dynamic value,
//   ) =>
//       super.noSuchMethod(
//         Invocation.method(
//           #setValueInStorage,
//           [
//             key,
//             value,
//           ],
//         ),
//         returnValueForMissingStub: null,
//       );

//   @override
//   _i3.Future<bool> setNewPin() => (super.noSuchMethod(
//         Invocation.method(
//           #setNewPin,
//           [],
//         ),
//         returnValue: _i3.Future<bool>.value(false),
//         returnValueForMissingStub: _i3.Future<bool>.value(false),
//       ) as _i3.Future<bool>);

//   @override
//   _i3.Future<bool> changePin() => (super.noSuchMethod(
//         Invocation.method(
//           #changePin,
//           [],
//         ),
//         returnValue: _i3.Future<bool>.value(false),
//         returnValueForMissingStub: _i3.Future<bool>.value(false),
//       ) as _i3.Future<bool>);

//   @override
//   _i3.Future<void> confirmPin(String? value) => (super.noSuchMethod(
//         Invocation.method(
//           #confirmPin,
//           [value],
//         ),
//         returnValue: _i3.Future<void>.value(),
//         returnValueForMissingStub: _i3.Future<void>.value(),
//       ) as _i3.Future<void>);

//   @override
//   _i3.Future<void> activateFingerPrint(bool? value) => (super.noSuchMethod(
//         Invocation.method(
//           #activateFingerPrint,
//           [value],
//         ),
//         returnValue: _i3.Future<void>.value(),
//         returnValueForMissingStub: _i3.Future<void>.value(),
//       ) as _i3.Future<void>);

//   @override
//   _i3.Future<bool> requestPinConfirmation(String? reason) =>
//       (super.noSuchMethod(
//         Invocation.method(
//           #requestPinConfirmation,
//           [reason],
//         ),
//         returnValue: _i3.Future<bool>.value(false),
//         returnValueForMissingStub: _i3.Future<bool>.value(false),
//       ) as _i3.Future<bool>);

//   @override
//   _i3.Future<bool> authenticateUser(String? reason) => (super.noSuchMethod(
//         Invocation.method(
//           #authenticateUser,
//           [reason],
//         ),
//         returnValue: _i3.Future<bool>.value(false),
//         returnValueForMissingStub: _i3.Future<bool>.value(false),
//       ) as _i3.Future<bool>);

//   @override
//   dynamic unlockWithFingerprint({bool? isSettingsFlow = false}) =>
//       super.noSuchMethod(
//         Invocation.method(
//           #unlockWithFingerprint,
//           [],
//           {#isSettingsFlow: isSettingsFlow},
//         ),
//         returnValueForMissingStub: null,
//       );

//   @override
//   void update([
//     List<Object>? ids,
//     bool? condition = true,
//   ]) =>
//       super.noSuchMethod(
//         Invocation.method(
//           #update,
//           [
//             ids,
//             condition,
//           ],
//         ),
//         returnValueForMissingStub: null,
//       );

//   @override
//   void onInit() => super.noSuchMethod(
//         Invocation.method(
//           #onInit,
//           [],
//         ),
//         returnValueForMissingStub: null,
//       );

//   @override
//   void onClose() => super.noSuchMethod(
//         Invocation.method(
//           #onClose,
//           [],
//         ),
//         returnValueForMissingStub: null,
//       );

//   @override
//   void $configureLifeCycle() => super.noSuchMethod(
//         Invocation.method(
//           #$configureLifeCycle,
//           [],
//         ),
//         returnValueForMissingStub: null,
//       );

//   @override
//   _i6.Disposer addListener(_i6.GetStateUpdate? listener) => (super.noSuchMethod(
//         Invocation.method(
//           #addListener,
//           [listener],
//         ),
//         returnValue: () {},
//         returnValueForMissingStub: () {},
//       ) as _i6.Disposer);

//   @override
//   void removeListener(_i7.VoidCallback? listener) => super.noSuchMethod(
//         Invocation.method(
//           #removeListener,
//           [listener],
//         ),
//         returnValueForMissingStub: null,
//       );

//   @override
//   void refresh() => super.noSuchMethod(
//         Invocation.method(
//           #refresh,
//           [],
//         ),
//         returnValueForMissingStub: null,
//       );

//   @override
//   void refreshGroup(Object? id) => super.noSuchMethod(
//         Invocation.method(
//           #refreshGroup,
//           [id],
//         ),
//         returnValueForMissingStub: null,
//       );

//   @override
//   void notifyChildrens() => super.noSuchMethod(
//         Invocation.method(
//           #notifyChildrens,
//           [],
//         ),
//         returnValueForMissingStub: null,
//       );

//   @override
//   void removeListenerId(
//     Object? id,
//     _i7.VoidCallback? listener,
//   ) =>
//       super.noSuchMethod(
//         Invocation.method(
//           #removeListenerId,
//           [
//             id,
//             listener,
//           ],
//         ),
//         returnValueForMissingStub: null,
//       );

//   @override
//   void dispose() => super.noSuchMethod(
//         Invocation.method(
//           #dispose,
//           [],
//         ),
//         returnValueForMissingStub: null,
//       );

//   @override
//   _i6.Disposer addListenerId(
//     Object? key,
//     _i6.GetStateUpdate? listener,
//   ) =>
//       (super.noSuchMethod(
//         Invocation.method(
//           #addListenerId,
//           [
//             key,
//             listener,
//           ],
//         ),
//         returnValue: () {},
//         returnValueForMissingStub: () {},
//       ) as _i6.Disposer);

//   @override
//   void disposeId(Object? id) => super.noSuchMethod(
//         Invocation.method(
//           #disposeId,
//           [id],
//         ),
//         returnValueForMissingStub: null,
//       );
// }
