// Run: dart run tool/parse_iso4217.dart < codes-all.csv > lib/constants/iso4217_currencies.gen.dart
// Download: curl -sLO https://raw.githubusercontent.com/datasets/currency-codes/master/data/codes-all.csv

import 'dart:io';

void main(List<String> args) {
  final String path = args.isNotEmpty ? args.first : 'codes-all.csv';
  final List<String> lines = File(path).readAsLinesSync();
  final Map<String, String> byCode = <String, String>{};
  for (int i = 1; i < lines.length; i++) {
    final List<String> row = _parseCsvLine(lines[i]);
    if (row.length < 6) continue;
    final String code = row[2].trim();
    if (code.length != 3 || !_isAlpha(code)) continue;
    if (row[5].trim().isNotEmpty) continue;
    final String name = row[1].trim();
    byCode.putIfAbsent(code, () => name);
  }
  final List<String> codes = byCode.keys.toList()..sort();
  final StringBuffer b = StringBuffer();
  b.writeln('// Generated by tool/parse_iso4217.dart — do not edit by hand.');
  b.writeln('');
  b.writeln('/// Picker entry: code + English name (ISO 4217 fiat; crypto uses the same type elsewhere).');
  b.writeln('class Iso4217Currency {');
  b.writeln('  const Iso4217Currency(this.code, this.name);');
  b.writeln('  final String code;');
  b.writeln('  final String name;');
  b.writeln('}');
  b.writeln('');
  b.writeln('const List<Iso4217Currency> kIso4217Currencies = <Iso4217Currency>[');
  for (final String code in codes) {
    final String name = _escapeDartStr(byCode[code]!);
    b.writeln("  Iso4217Currency('$code', '$name'),");
  }
  b.writeln('];');
  stdout.write(b.toString());
}

bool _isAlpha(String s) {
  for (int i = 0; i < s.length; i++) {
    final int c = s.codeUnitAt(i);
    if (c < 65 || c > 90) return false;
  }
  return true;
}

String _escapeDartStr(String s) {
  return s.replaceAll(r'\', r'\\').replaceAll("'", r"\'");
}

/// Minimal CSV parser for this dataset (handles quoted fields).
List<String> _parseCsvLine(String line) {
  final List<String> out = <String>[];
  final StringBuffer cur = StringBuffer();
  bool inQ = false;
  for (int i = 0; i < line.length; i++) {
    final String ch = line[i];
    if (inQ) {
      if (ch == '"') {
        if (i + 1 < line.length && line[i + 1] == '"') {
          cur.write('"');
          i++;
        } else {
          inQ = false;
        }
      } else {
        cur.write(ch);
      }
    } else {
      if (ch == '"') {
        inQ = true;
      } else if (ch == ',') {
        out.add(cur.toString());
        cur.clear();
      } else {
        cur.write(ch);
      }
    }
  }
  out.add(cur.toString());
  return out;
}
